# Generated by Django 2.2.28 on 2023-03-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureName', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='post_images')),
                ('description', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_spaces_app.Category')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_spaces_app.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('userProfile', models.ImageField(blank=True, upload_to='profile_images')),
                ('email', models.EmailField(max_length=50)),
                ('userType', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_spaces_app.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_spaces_app.Post')),
            ],
        ),
    ]
