# Generated by Django 2.2.28 on 2023-03-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
