# Generated by Django 2.2.28 on 2023-03-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0002_auto_20230311_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserProfile',
        ),
    ]
