# Generated by Django 2.2.28 on 2023-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0004_remove_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userName',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('student', 'I am a student'), ('business', 'I am not a student')], max_length=10),
        ),
    ]
