# Generated by Django 2.2.28 on 2023-03-16 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0007_auto_20230313_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='UserProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study_spaces_app.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='UserProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study_spaces_app.UserProfile'),
            preserve_default=False,
        ),
    ]
