# Generated by Django 2.2.28 on 2023-03-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0008_auto_20230316_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='UserProfile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='study_spaces_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='UserProfile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='study_spaces_app.UserProfile'),
        ),
    ]
