# Generated by Django 2.2.28 on 2023-03-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0011_auto_20230316_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='UserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_spaces_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='UserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_spaces_app.UserProfile'),
        ),
    ]
