# Generated by Django 2.2.28 on 2023-03-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0015_auto_20230316_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('Student', 'student'), ('Business', 'business')], max_length=10),
        ),
    ]
