# Generated by Django 2.2.28 on 2023-03-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0016_auto_20230316_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('Student', 'Student'), ('Business', 'Business')], max_length=10),
        ),
    ]
