# Generated by Django 2.2.28 on 2023-03-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0019_auto_20230316_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userProfile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userProfile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userProfile',
            new_name='user_profile',
        ),
    ]
