# Generated by Django 2.2.28 on 2023-03-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0020_auto_20230316_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
