# Generated by Django 2.2.28 on 2023-03-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0023_delete_postlike'),
        ('study_spaces_app', '0021_auto_20230322_2158'),
    ]

    operations = [
    ]
