# Generated by Django 2.2.28 on 2023-03-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0024_merge_20230323_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
