# Generated by Django 2.2.28 on 2023-03-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_spaces_app', '0025_auto_20230323_2215'),
        ('study_spaces_app', '0025_auto_20230323_2230'),
    ]

    operations = [
    ]
